import { Geist, Geist_Mono } from "next/font/google";
import localfont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const satoshi=localfont({
  name: "Satoshi",
  src:[{
    path:"../../public/fonts/Satoshi-Regular.ttf",
    weight:"400"
  },],
  variable: "--font-satoshi",
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  className={`${satoshi.variable} font-satoshi`}>
      <body
        className={`${satoshi.variable} font-satoshi antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
